@echo off
setlocal enabledelayedexpansion

:: ==============================
:: Project Folder Generator + README + SUBFOLDER
:: ==============================

:: Ask for project name
echo Project Folder Generator
set /p PROJECT_NAME=Enter project name: 

:: Check if empty
if "%PROJECT_NAME%"=="" (
    echo Project name cannot be empty!
    pause
    exit /b
)

:: Ask for creator name
set /p CREATOR_NAME=Enter your name: 

:: Check if empty
if "%CREATOR_NAME%"=="" (
    echo Your name cannot be empty!
    pause
    exit /b
)

:: Create main folder
mkdir "%PROJECT_NAME%"

:: ==============================
:: Main subfolders
:: ==============================
mkdir "%PROJECT_NAME%\00_concept\01_art"
mkdir "%PROJECT_NAME%\00_concept\02_script"
mkdir "%PROJECT_NAME%\00_concept\03_storyboard"
mkdir "%PROJECT_NAME%\00_concept\04_animatics"
mkdir "%PROJECT_NAME%\00_concept\05_reference"

mkdir "%PROJECT_NAME%\01_assets\01_prop"
mkdir "%PROJECT_NAME%\01_assets\02_char"
mkdir "%PROJECT_NAME%\01_assets\03_environment"
mkdir "%PROJECT_NAME%\01_assets\04_hdri"
mkdir "%PROJECT_NAME%\01_assets\05_footage"
mkdir "%PROJECT_NAME%\01_assets\06_video"
mkdir "%PROJECT_NAME%\01_assets\07_library"

mkdir "%PROJECT_NAME%\02_layout\preview"

mkdir "%PROJECT_NAME%\03_animation\preview"

mkdir "%PROJECT_NAME%\04_vfx\preview"

mkdir "%PROJECT_NAME%\05_lighting\preview"

mkdir "%PROJECT_NAME%\06_render"

mkdir "%PROJECT_NAME%\07_compositing\01_file"
mkdir "%PROJECT_NAME%\07_compositing\02_output"

mkdir "%PROJECT_NAME%\08_editing\preview"

mkdir "%PROJECT_NAME%\09_sound"

mkdir "%PROJECT_NAME%\10_final"

mkdir "%PROJECT_NAME%\11_temp"

mkdir "%PROJECT_NAME%\12_sync"

mkdir "%PROJECT_NAME%\99_research"

:: ==============================
:: Create README.txt
:: ==============================
set "README_FILE=%PROJECT_NAME%\README.txt"

:: Get date and time
set TANGGAL=%date:~6,4%-%date:~3,2%-%date:~0,2%
set JAM=%time:~0,2%-%time:~3,2%-%time:~6,2%

:: Remove space in front of hour (if < 10)
if "%JAM:~0,1%"==" " set JAM=0%JAM:~1%

if not exist "%README_FILE%" (
    echo Creating README...
    > "%README_FILE%" (
        echo ==============================
        echo   PROJECT FOLDERING GUIDELINES
        echo ==============================
        echo.
        echo 00_concept
        echo  ├─ 01_art            = Concept art, initial visual ideas
        echo  ├─ 02_script         = Story or screenplay script
        echo  ├─ 03_storyboard     = Visual storyboard
        echo  ├─ 04_animatics      = Animatics / pre-visual animation
        echo  └─ 05_reference      = Collection of supporting references
        echo.
        echo 01_assets
        echo  ├─ 01_prop           = Props models or assets
        echo  ├─ 02_char           = Character assets
        echo  ├─ 03_environment    = Environment assets
        echo  ├─ 04_hdri           = HDRI for lighting
        echo  ├─ 05_footage        = Raw footage / recordings
        echo  ├─ 06_video          = Supporting videos
        echo  └─ 07_library        = Additional asset library
        echo.
        echo 02_layout
        echo  └─ preview           = Layout preview
        echo.
        echo 03_animation
        echo  └─ preview           = Animation preview
        echo.
        echo 04_vfx
        echo  └─ preview           = VFX preview
        echo.
        echo 05_lighting
        echo  └─ preview           = Lighting preview
        echo.
        echo 06_render             = Final render outputs
        echo.
        echo 07_compositing
        echo  ├─ 01_file           = Compositing files
        echo  └─ 02_output         = Compositing outputs
        echo.
        echo 08_editing
        echo  └─ preview           = Editing preview
        echo.
        echo 09_sound              = Sound assets, music, SFX
        echo.
        echo 10_final              = Final project outputs
        echo.
        echo 11_temp               = Temporary files / cache
        echo.
        echo 12_sync               = Sync folder ^(collaboration / backup^)
        echo.
        echo 99_research           = Research and experiments folder
        echo.
        echo ================================================================================
        echo   note: if there are version changes of files, please add _v001 / _v002 at the end
        echo ================================================================================
        echo.
        echo ==============================
        echo   Automatically generated by script
        echo ==============================
        echo.
        echo ============================================================
        echo   Created on : %TANGGAL% %JAM%, by %CREATOR_NAME%
        echo ============================================================
        echo.
    )
)

echo.
echo Foldering for "%PROJECT_NAME%" has been successfully created!
echo README.txt has been added inside the project folder.
pause
